export type BrandItem = {
  id: number;
  name: string;
  hint: string;
  slug: string;
  accent: string;
  iconUrl: string;
  surface: 'clear' | 'porcelain';
};

const LOGO_EXTENSIONS: Record<string, string> = {
  cloudflare: 'png',
  gmail: 'png',
  google: 'png',
  googledocs: 'png',
  googledrive: 'png',
  googlekeep: 'png',
  googlesheets: 'png',
  googleslides: 'png',
  wordpress: 'png'
};

const PORCELAIN_LOGOS = new Set([
  'amazonwebservices',
  'basecamp',
  'buffer',
  'hootsuite',
  'ifttt',
  'openai',
  'squarespace',
  'typeform',
  'x',
  'zendesk'
]);

const iconUrl = (slug: string) =>
  `/brand-logos/${slug}.${LOGO_EXTENSIONS[slug] ?? 'svg'}`;

const brand = (
  id: number,
  name: string,
  hint: string,
  slug: string,
  accent: string
): BrandItem => ({
  id,
  name,
  hint,
  slug,
  accent,
  iconUrl: iconUrl(slug),
  surface: PORCELAIN_LOGOS.has(slug) ? 'porcelain' : 'clear'
});

export const BRANDS: BrandItem[] = [
  brand(0, 'ChatGPT', 'Prompts', 'openai', '#74AA9C'),
  brand(1, 'Claude', 'Thinking', 'anthropic', '#D97757'),
  brand(2, 'Gemini', 'Research', 'googlegemini', '#8E75B2'),
  brand(125, 'Google', 'Search', 'google', '#4285F4'),
  brand(3, 'Perplexity', 'Answers', 'perplexity', '#20B8CD'),
  brand(4, 'Gmail', 'Replies', 'gmail', '#EA4335'),
  brand(5, 'Outlook', 'Email', 'microsoftoutlook', '#0078D4'),
  brand(6, 'Google Docs', 'Docs', 'googledocs', '#4285F4'),
  brand(7, 'Google Sheets', 'Sheets', 'googlesheets', '#34A853'),
  brand(8, 'Google Slides', 'Slides', 'googleslides', '#FBBC04'),
  brand(9, 'LinkedIn', 'Posts', 'linkedin', '#0A66C2'),
  brand(10, 'X', 'Threads', 'x', '#E7E9EA'),
  brand(11, 'Discord', 'DMs', 'discord', '#5865F2'),
  brand(12, 'Slack', 'Chat', 'slack', '#E01E5A'),
  brand(13, 'Telegram', 'Messages', 'telegram', '#26A5E4'),
  brand(14, 'WhatsApp', 'Chat', 'whatsapp', '#25D366'),
  brand(15, 'YouTube', 'Comments', 'youtube', '#FF0000'),
  brand(16, 'Reddit', 'Posts', 'reddit', '#FF4500'),
  brand(17, 'Medium', 'Articles', 'medium', '#E8EDF5'),
  brand(18, 'Notion', 'Notes', 'notion', '#E8EDF5'),
  brand(19, 'Word', 'Docs', 'microsoftword', '#2B579A'),
  brand(20, 'Figma', 'Comments', 'figma', '#F24E1E'),
  brand(21, 'VS Code', 'Code', 'visualstudiocode', '#007ACC'),
  brand(22, 'Chrome', 'Browser', 'googlechrome', '#FBBC04'),
  brand(23, 'Teams', 'Meetings', 'microsoftteams', '#6264A7'),
  brand(24, 'Zoom', 'Calls', 'zoom', '#2D8CFF'),
  brand(25, 'Trello', 'Cards', 'trello', '#0052CC'),
  brand(26, 'Asana', 'Tasks', 'asana', '#F06A6A'),
  brand(27, 'Jira', 'Issues', 'jira', '#2684FF'),
  brand(28, 'GitHub', 'Code', 'github', '#F0F6FC'),
  brand(29, 'GitLab', 'Code', 'gitlab', '#FC6D26'),
  brand(30, 'Stack Overflow', 'Answers', 'stackoverflow', '#F48024'),
  brand(31, 'Apple Notes', 'Notes', 'apple', '#E8EDF5'),
  brand(32, 'Obsidian', 'Knowledge', 'obsidian', '#8B5CF6'),
  brand(33, 'Facebook', 'Social', 'facebook', '#1877F2'),
  brand(34, 'Instagram', 'Social', 'instagram', '#E4405F'),
  brand(35, 'TikTok', 'Social', 'tiktok', '#FE2C55'),
  brand(36, 'Pinterest', 'Ideas', 'pinterest', '#BD081C'),
  brand(37, 'Snapchat', 'Social', 'snapchat', '#FFFC00'),
  brand(38, 'Threads', 'Social', 'threads', '#E8EDF5'),
  brand(39, 'Mastodon', 'Social', 'mastodon', '#6364FF'),
  brand(40, 'Bluesky', 'Social', 'bluesky', '#1185FE'),
  brand(41, 'Product Hunt', 'Launches', 'producthunt', '#DA552F'),
  brand(42, 'Dribbble', 'Design', 'dribbble', '#EA4C89'),
  brand(43, 'Behance', 'Design', 'behance', '#1769FF'),
  brand(44, 'Canva', 'Design', 'canva', '#00C4CC'),
  brand(45, 'Dropbox', 'Files', 'dropbox', '#0061FF'),
  brand(46, 'Google Drive', 'Files', 'googledrive', '#4285F4'),
  brand(47, 'OneDrive', 'Files', 'microsoftonedrive', '#0078D4'),
  brand(48, 'Box', 'Files', 'box', '#0061D5'),
  brand(49, 'Evernote', 'Notes', 'evernote', '#00A82D'),
  brand(50, 'Todoist', 'Tasks', 'todoist', '#E44332'),
  brand(51, 'ClickUp', 'Tasks', 'clickup', '#7B68EE'),
  brand(52, 'Airtable', 'Data', 'airtable', '#18BFFF'),
  brand(53, 'Miro', 'Boards', 'miro', '#FFD02F'),
  brand(54, 'Linear', 'Issues', 'linear', '#5E6AD2'),
  brand(55, 'Basecamp', 'Projects', 'basecamp', '#1D2D35'),
  brand(56, 'Confluence', 'Docs', 'confluence', '#172B4D'),
  brand(57, 'Bitbucket', 'Code', 'bitbucket', '#0052CC'),
  brand(58, 'Git', 'Code', 'git', '#F05032'),
  brand(59, 'Docker', 'Dev', 'docker', '#2496ED'),
  brand(60, 'Kubernetes', 'Dev', 'kubernetes', '#326CE5'),
  brand(61, 'AWS', 'Cloud', 'amazonwebservices', '#FF9900'),
  brand(62, 'Google Cloud', 'Cloud', 'googlecloud', '#4285F4'),
  brand(63, 'Cloudflare', 'Web', 'cloudflare', '#F38020'),
  brand(64, 'Vercel', 'Deploy', 'vercel', '#E8EDF5'),
  brand(65, 'Netlify', 'Deploy', 'netlify', '#00C7B7'),
  brand(66, 'Heroku', 'Deploy', 'heroku', '#430098'),
  brand(67, 'DigitalOcean', 'Cloud', 'digitalocean', '#0080FF'),
  brand(68, 'Firebase', 'Data', 'firebase', '#FFCA28'),
  brand(69, 'Supabase', 'Data', 'supabase', '#3FCF8E'),
  brand(70, 'PostgreSQL', 'Data', 'postgresql', '#4169E1'),
  brand(71, 'MySQL', 'Data', 'mysql', '#4479A1'),
  brand(72, 'MongoDB', 'Data', 'mongodb', '#47A248'),
  brand(73, 'Redis', 'Data', 'redis', '#DC382D'),
  brand(74, 'Elasticsearch', 'Search', 'elasticsearch', '#005571'),
  brand(75, 'Python', 'Code', 'python', '#3776AB'),
  brand(76, 'JavaScript', 'Code', 'javascript', '#F7DF1E'),
  brand(77, 'TypeScript', 'Code', 'typescript', '#3178C6'),
  brand(78, 'React', 'Code', 'react', '#61DAFB'),
  brand(79, 'Next.js', 'Code', 'nextdotjs', '#E8EDF5'),
  brand(80, 'Vue', 'Code', 'vuedotjs', '#4FC08D'),
  brand(81, 'Angular', 'Code', 'angular', '#DD0031'),
  brand(82, 'Svelte', 'Code', 'svelte', '#FF3E00'),
  brand(83, 'Tailwind CSS', 'Code', 'tailwindcss', '#06B6D4'),
  brand(84, 'npm', 'Packages', 'npm', '#CB3837'),
  brand(85, 'Yarn', 'Packages', 'yarn', '#2C8EBB'),
  brand(86, 'pnpm', 'Packages', 'pnpm', '#F69220'),
  brand(87, 'HTML5', 'Web', 'html5', '#E34F26'),
  brand(88, 'CSS', 'Web', 'css', '#663399'),
  brand(89, 'Sass', 'Web', 'sass', '#CC6699'),
  brand(90, 'Webflow', 'Sites', 'webflow', '#146EF5'),
  brand(91, 'WordPress', 'Sites', 'wordpress', '#21759B'),
  brand(92, 'Shopify', 'Commerce', 'shopify', '#7AB55C'),
  brand(93, 'Stripe', 'Payments', 'stripe', '#635BFF'),
  brand(94, 'PayPal', 'Payments', 'paypal', '#003087'),
  brand(95, 'Square', 'Payments', 'square', '#3E4348'),
  brand(96, 'QuickBooks', 'Finance', 'quickbooks', '#2CA01C'),
  brand(97, 'HubSpot', 'CRM', 'hubspot', '#FF7A59'),
  brand(98, 'Salesforce', 'CRM', 'salesforce', '#00A1E0'),
  brand(99, 'Mailchimp', 'Email', 'mailchimp', '#FFE01B'),
  brand(100, 'Zendesk', 'Support', 'zendesk', '#03363D'),
  brand(101, 'Intercom', 'Support', 'intercom', '#6AFDEF'),
  brand(102, 'Calendly', 'Calendar', 'calendly', '#006BFF'),
  brand(103, 'Typeform', 'Forms', 'typeform', '#E8EDF5'),
  brand(104, 'SurveyMonkey', 'Forms', 'surveymonkey', '#00BF6F'),
  brand(105, 'Grammarly', 'Writing', 'grammarly', '#15C39A'),
  brand(106, 'Google Keep', 'Notes', 'googlekeep', '#FFBB00'),
  brand(107, 'Skype', 'Calls', 'skype', '#00AFF0'),
  brand(108, 'SharePoint', 'Docs', 'microsoftsharepoint', '#0078D4'),
  brand(109, 'Notepad++', 'Writing', 'notepadplusplus', '#90E59A'),
  brand(110, 'Adobe Acrobat', 'PDFs', 'adobeacrobatreader', '#EC1C24'),
  brand(111, 'Photoshop', 'Design', 'adobephotoshop', '#31A8FF'),
  brand(112, 'Illustrator', 'Design', 'adobeillustrator', '#FF9A00'),
  brand(113, 'Premiere Pro', 'Video', 'adobepremierepro', '#9999FF'),
  brand(114, 'After Effects', 'Video', 'adobeaftereffects', '#9999FF'),
  brand(115, 'Wix', 'Sites', 'wix', '#0C6EFC'),
  brand(116, 'Squarespace', 'Sites', 'squarespace', '#E8EDF5'),
  brand(117, 'Zapier', 'Automation', 'zapier', '#FF4F00'),
  brand(118, 'IFTTT', 'Automation', 'ifttt', '#E8EDF5'),
  brand(119, 'Buffer', 'Social', 'buffer', '#231F20'),
  brand(120, 'Hootsuite', 'Social', 'hootsuite', '#143059'),
  brand(121, 'Loom', 'Video', 'loom', '#625DF5'),
  brand(122, 'DocuSign', 'Documents', 'docusign', '#FFCC22'),
  brand(123, 'Twilio', 'Messaging', 'twilio', '#F22F46'),
  brand(124, 'SendGrid', 'Email', 'sendgrid', '#1A82E2'),
  brand(126, 'DeepSeek', 'AI chat', 'deepseek', '#4D6BFE'),
  brand(127, 'Microsoft Copilot', 'AI assistant', 'microsoftcopilot', '#00AEFF'),
  brand(128, 'DeepL', 'Translation', 'deepl', '#0F2B46'),
  brand(129, 'Hugging Face', 'AI models', 'huggingface', '#FFD21E'),
  brand(130, 'Google Meet', 'Meetings', 'googlemeet', '#00AC47'),
  brand(131, 'Google Calendar', 'Calendar', 'googlecalendar', '#4285F4')
];

export const BRAND_WALL: BrandItem[] = BRANDS;
